### ISSUE TITLE
Use wrong variable to calculate probability

### ISSUE THREAD

**Issue by mics8128** [kuohsuanlo/orereplacer#3]
https://github.com/kuohsuanlo/orereplacer/blob/31653764f36a374b871e90ea00e11ba6f5111fde/src/main/java/io/github/kuohsuanlo/orereplacer/OreReplacerPlugin.java#L226

should be ``MIN_EMERALD`` but it is ``MIN_REDSTONE``

**Comment by kuohsuanlo** [comment]
Thanks for reporting, should be fixed soon.
