### ISSUE TITLE
严重的安全隐患

### ISSUE THREAD

**Issue by Vlvxingze** [kuohsuanlo/orereplacer#9]
呃，我用这个插件快几个月了，近日玩家反馈给我我才注意到这个极其严重的隐患
我服是一个末日服，配有怪物攻城和粘液科技等物品拓展包
玩家们告诉我，假矿只有被挖了才刷新，
因此如果使用破障弓箭，怪物破坏方块等等
矿物就不会被刷新，导致假矿变成真矿
玩家已经利用这个bug刷了好多的矿。

**Comment by kuohsuanlo** [comment]
1. 這並不是「安全」隱患，這是插件之間的支援度問題。
2. 我並沒有支援其他模式，只有原味生存。如果有需要可以自行fork修改，或是改用傳統x-ray。
